# Generated by Django 3.1.4 on 2020-12-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201218_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
