# Generated by Django 3.1.4 on 2020-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MAN', 'Project Manager'), ('SUB', 'Submitter'), ('DEV', 'Developer')], default='ADMIN', max_length=20),
        ),
    ]
