# Generated by Django 3.1.4 on 2020-12-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201221_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrole',
            old_name='role',
            new_name='user_role',
        ),
    ]
