# Generated by Django 3.1.4 on 2020-12-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201221_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MAN', 'Project Manager'), ('SUB', 'Submitter'), ('DEV', 'Developer')], default='DEV', max_length=20),
        ),
    ]
