# Generated by Django 3.1.4 on 2020-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201224_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MAN', 'Project Manager')], default='MAN', max_length=20),
        ),
    ]
