# Generated by Django 3.1.4 on 2020-12-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201225_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Member', 'Member')], default='MEM', max_length=20),
        ),
    ]
