# Generated by Django 3.1.4 on 2020-12-17 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20201216_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('priority', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NONE', max_length=12)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In_Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=12)),
                ('class_type', models.CharField(choices=[('TASK', 'Task'), ('BUG', 'Bug'), ('CHANGE', 'Change'), ('FEATURE', 'Feature_request')], default='TASK', max_length=12)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.project')),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('body_message', models.CharField(max_length=50)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('note', models.CharField(max_length=30)),
                ('attachment', models.FileField(upload_to='')),
                ('submitted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
