# Generated by Django 3.1.4 on 2020-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='note',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='body_message',
            field=models.CharField(max_length=60),
        ),
    ]
