# Generated by Django 3.1.4 on 2020-12-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='user',
        ),
    ]
