# Generated by Django 3.1.4 on 2020-12-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20201218_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketAttachment',
        ),
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
