# Generated by Django 3.1.4 on 2020-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='note',
            field=models.CharField(max_length=150),
        ),
    ]
