# Generated by Django 3.1.4 on 2020-12-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20201219_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='status',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=6),
        ),
    ]
