# Generated by Django 3.1.4 on 2021-01-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.CharField(max_length=80),
        ),
    ]
