# Generated by Django 3.1.4 on 2021-01-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210102_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('COM', 'Complete'), ('SCH', 'Scheduled')], default='SCH', max_length=6),
        ),
    ]
