# Generated by Django 3.1.4 on 2021-01-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('SCH', 'Scheduled')], default='SCH', max_length=6),
        ),
    ]
