# Generated by Django 3.1.4 on 2021-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20210105_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
