# Generated by Django 3.1.4 on 2020-12-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20201216_2201'),
        ('projects', '0002_auto_20201218_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('priority', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NONE', max_length=12)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In_Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=12)),
                ('class_type', models.CharField(choices=[('TASK', 'Task'), ('BUG', 'Bug'), ('CHANGE', 'Change'), ('FEATURE', 'Feature_request')], default='TASK', max_length=12)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to='account.profile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('body_message', models.CharField(max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('note', models.CharField(max_length=70)),
                ('attachment', models.FileField(upload_to='')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
