# Generated by Django 3.1.4 on 2020-12-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='class_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('BUG', 'Bug'), ('CHANGE', 'Change'), ('FEATURE', 'Feature request')], default='TASK', max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=12),
        ),
    ]
