# Generated by Django 3.1.4 on 2020-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignee',
            name='user_role',
            field=models.CharField(choices=[('SUB', 'Submitter'), ('DEV', 'Developer')], default='DEV', max_length=20),
        ),
    ]
