# Generated by Django 3.1.4 on 2020-12-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20201226_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketattachment',
            old_name='submitted_by',
            new_name='user',
        ),
    ]
