# Generated by Django 3.1.4 on 2020-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20201226_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='note',
            field=models.CharField(max_length=100),
        ),
    ]
