# Generated by Django 3.1.4 on 2020-12-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20201226_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketassignee',
            name='user_role',
        ),
    ]
